### ISSUE TITLE
NodeOutputPlot's updateColor(_:) doesn't work

### ISSUE THREAD

**Issue by Lascorbe** [AudioKit/AudioKitUI#16]
But `.color` does work, so I think the method `updateColor(_:)` can be marked as deprecated?

**Comment by emurray2** [comment]
It looks like NodeOutputPlot was deprecated in this commit: https://github.com/AudioKit/AudioKitUI/commit/6aaefe66ac5dcd8bcbb0a249b09a66e1d8e7f561 . Although, there's a new `SwiftUI` based `NodeOutputView` which has its `color` passed through the initializer.
