### ISSUE TITLE
XCode 13 / iOS15 - Build error

### ISSUE THREAD

**Issue by lukecsmith** [AudioKit/AudioKitUI#19]
Attempting to build for XCode 13 Beta, theres a build error in MIDITrackView - same issue in 4 separate places.  Line 106, 175, 190, 207 : cursorTime = .. compiler is unable to debug this line in reasonable time.  Equation needs splitting up into smaller parts.  I'll happily do this myself if I can contribute?  thanks, Luke

**Comment by lukecsmith** [comment]
Ive fixed this issue here: 
[MIDITrackView.swift.zip](https://github.com/AudioKit/AudioKitUI/files/6740581/MIDITrackView.swift.zip)

**Comment by aure** [comment]
Do you want to create a PR or should I just make the fix from your zip?

**Comment by lukecsmith** [comment]
hey there, Ive made a PR, thanks https://github.com/AudioKit/AudioKitUI/pull/20
