### ISSUE TITLE
how to add NodeOutputView  as a subview. It used to work before

### ISSUE THREAD

**Issue by vittalk** [AudioKit/AudioKitUI#36]
Hi, 
The following code used to compile and work a few months earlier (on XCode 12.5). Now, on a new mac (Monterrey and XCode 13.1) I get  the following error. Any help.  My AudioKit / AudioKitUI versions were set to 'main branch'.
   "Cannot convert value of type 'NodeOutputView?' to expected argument type 'UIView' 

       var audioMic_liveView2: NodeOutputView!
       audioMic_liveView2 = NodeOutputView(self.conductor_2.tappableNodeA)
        audioMic_liveView.addSubview(audioMic_liveView2)                      <-- shows the above error

**Comment by aure** [comment]
You'll have to wrap the SwiftUI View (nodeOutputView) into a UIView.
