### ISSUE TITLE
KnobView example, changing color, size, and other properties

### ISSUE THREAD

**Issue by scottmetoyer** [AudioKit/AudioKitUI#39]
I'm quite new to AudioKit and Swift programming in general. It doesn't appear to be possible to change the size, color, and other properties of a KnobView - is this accurate? If not are there any examples of using a KnobView?  I didn't see anything in the Cookbook.

Thanks!

**Comment by analogcode** [comment]
Hey Scott!
There's a couple of other code examples of knobs on my personal github. They're a bit older, though

using images:
https://github.com/analogcode/3D-Knobs

using paintcode:
https://github.com/analogcode/SynthKnobExample

**Comment by aure** [comment]
We removed all the knobs here and now we're putting all future controls in https://github.com/AudioKit/Controls
